//! Auto-generated Godot 4.6 class database.
//! Source: Godot extension_api.json (hand-curated subset)
//! Regenerate: python tools/generate_class_db.py extension_api.json > src/class_db/generated.rs

pub struct ClassInfo {
    pub name: &'static str,
    pub parent: &'static str,
    pub is_virtual: bool,
}

/// Sorted by name for binary search.
pub static CLASSES: &[ClassInfo] = &[
    ClassInfo {
        name: "AcceptDialog",
        parent: "Window",
        is_virtual: false,
    },
    ClassInfo {
        name: "AnimatableBody2D",
        parent: "StaticBody2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "AnimatableBody3D",
        parent: "StaticBody3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "AnimatedSprite2D",
        parent: "Node2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "AnimatedSprite3D",
        parent: "SpriteBase3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "AnimatedTexture",
        parent: "Texture2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "AnimationLibrary",
        parent: "Resource",
        is_virtual: false,
    },
    ClassInfo {
        name: "AnimationMixer",
        parent: "Node",
        is_virtual: false,
    },
    ClassInfo {
        name: "AnimationPlayer",
        parent: "AnimationMixer",
        is_virtual: false,
    },
    ClassInfo {
        name: "AnimationTree",
        parent: "AnimationMixer",
        is_virtual: false,
    },
    ClassInfo {
        name: "Area2D",
        parent: "CollisionObject2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "Area3D",
        parent: "CollisionObject3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "ArrayMesh",
        parent: "Mesh",
        is_virtual: false,
    },
    ClassInfo {
        name: "AspectRatioContainer",
        parent: "Container",
        is_virtual: false,
    },
    ClassInfo {
        name: "AudioBusLayout",
        parent: "Resource",
        is_virtual: false,
    },
    ClassInfo {
        name: "AudioEffect",
        parent: "Resource",
        is_virtual: false,
    },
    ClassInfo {
        name: "AudioStream",
        parent: "Resource",
        is_virtual: false,
    },
    ClassInfo {
        name: "AudioStreamPlayer",
        parent: "Node",
        is_virtual: false,
    },
    ClassInfo {
        name: "AudioStreamPlayer2D",
        parent: "Node2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "AudioStreamPlayer3D",
        parent: "Node3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "BaseButton",
        parent: "Control",
        is_virtual: false,
    },
    ClassInfo {
        name: "BaseMaterial3D",
        parent: "Material",
        is_virtual: false,
    },
    ClassInfo {
        name: "BitMap",
        parent: "Resource",
        is_virtual: false,
    },
    ClassInfo {
        name: "Bone2D",
        parent: "Node2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "BoneAttachment3D",
        parent: "Node3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "BoxContainer",
        parent: "Container",
        is_virtual: false,
    },
    ClassInfo {
        name: "BoxMesh",
        parent: "PrimitiveMesh",
        is_virtual: false,
    },
    ClassInfo {
        name: "BoxShape3D",
        parent: "Shape3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "Button",
        parent: "BaseButton",
        is_virtual: false,
    },
    ClassInfo {
        name: "CPUParticles2D",
        parent: "Node2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "CPUParticles3D",
        parent: "Node3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "Camera2D",
        parent: "Node2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "Camera3D",
        parent: "Node3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "CanvasGroup",
        parent: "Node2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "CanvasItem",
        parent: "Node",
        is_virtual: false,
    },
    ClassInfo {
        name: "CanvasLayer",
        parent: "Node",
        is_virtual: false,
    },
    ClassInfo {
        name: "CapsuleMesh",
        parent: "PrimitiveMesh",
        is_virtual: false,
    },
    ClassInfo {
        name: "CapsuleShape2D",
        parent: "Shape2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "CapsuleShape3D",
        parent: "Shape3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "CenterContainer",
        parent: "Container",
        is_virtual: false,
    },
    ClassInfo {
        name: "CharacterBody2D",
        parent: "PhysicsBody2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "CharacterBody3D",
        parent: "PhysicsBody3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "CheckBox",
        parent: "Button",
        is_virtual: false,
    },
    ClassInfo {
        name: "CheckButton",
        parent: "Button",
        is_virtual: false,
    },
    ClassInfo {
        name: "CircleShape2D",
        parent: "Shape2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "CodeEdit",
        parent: "TextEdit",
        is_virtual: false,
    },
    ClassInfo {
        name: "CollisionObject2D",
        parent: "Node2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "CollisionObject3D",
        parent: "Node3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "CollisionPolygon2D",
        parent: "Node2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "CollisionPolygon3D",
        parent: "Node3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "CollisionShape2D",
        parent: "Node2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "CollisionShape3D",
        parent: "Node3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "ColorPickerButton",
        parent: "Button",
        is_virtual: false,
    },
    ClassInfo {
        name: "ColorRect",
        parent: "Control",
        is_virtual: false,
    },
    ClassInfo {
        name: "CompressedTexture2D",
        parent: "Texture2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "ConcavePolygonShape2D",
        parent: "Shape2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "ConcavePolygonShape3D",
        parent: "Shape3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "ConfirmationDialog",
        parent: "AcceptDialog",
        is_virtual: false,
    },
    ClassInfo {
        name: "Container",
        parent: "Control",
        is_virtual: false,
    },
    ClassInfo {
        name: "Control",
        parent: "CanvasItem",
        is_virtual: false,
    },
    ClassInfo {
        name: "ConvexPolygonShape2D",
        parent: "Shape2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "ConvexPolygonShape3D",
        parent: "Shape3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "CurveTexture",
        parent: "Texture2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "CylinderMesh",
        parent: "PrimitiveMesh",
        is_virtual: false,
    },
    ClassInfo {
        name: "CylinderShape3D",
        parent: "Shape3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "DirectionalLight2D",
        parent: "Light2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "DirectionalLight3D",
        parent: "Light3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "Environment",
        parent: "Resource",
        is_virtual: false,
    },
    ClassInfo {
        name: "FileDialog",
        parent: "ConfirmationDialog",
        is_virtual: false,
    },
    ClassInfo {
        name: "FlowContainer",
        parent: "Container",
        is_virtual: false,
    },
    ClassInfo {
        name: "FogVolume",
        parent: "VisualInstance3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "Font",
        parent: "Resource",
        is_virtual: false,
    },
    ClassInfo {
        name: "FontFile",
        parent: "Font",
        is_virtual: false,
    },
    ClassInfo {
        name: "FontVariation",
        parent: "Font",
        is_virtual: false,
    },
    ClassInfo {
        name: "GPUParticles2D",
        parent: "Node2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "GPUParticles3D",
        parent: "Node3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "GeometryInstance3D",
        parent: "VisualInstance3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "GradientTexture1D",
        parent: "Texture2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "GradientTexture2D",
        parent: "Texture2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "GraphEdit",
        parent: "Control",
        is_virtual: false,
    },
    ClassInfo {
        name: "GraphElement",
        parent: "Container",
        is_virtual: false,
    },
    ClassInfo {
        name: "GraphNode",
        parent: "GraphElement",
        is_virtual: false,
    },
    ClassInfo {
        name: "GridContainer",
        parent: "Container",
        is_virtual: false,
    },
    ClassInfo {
        name: "GridMap",
        parent: "Node3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "HBoxContainer",
        parent: "BoxContainer",
        is_virtual: false,
    },
    ClassInfo {
        name: "HFlowContainer",
        parent: "FlowContainer",
        is_virtual: false,
    },
    ClassInfo {
        name: "HScrollBar",
        parent: "ScrollBar",
        is_virtual: false,
    },
    ClassInfo {
        name: "HSeparator",
        parent: "Separator",
        is_virtual: false,
    },
    ClassInfo {
        name: "HSlider",
        parent: "Slider",
        is_virtual: false,
    },
    ClassInfo {
        name: "HSplitContainer",
        parent: "SplitContainer",
        is_virtual: false,
    },
    ClassInfo {
        name: "HTTPRequest",
        parent: "Node",
        is_virtual: false,
    },
    ClassInfo {
        name: "Image",
        parent: "Resource",
        is_virtual: false,
    },
    ClassInfo {
        name: "ImageTexture",
        parent: "Texture2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "ItemList",
        parent: "Control",
        is_virtual: false,
    },
    ClassInfo {
        name: "Joint2D",
        parent: "Node2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "Joint3D",
        parent: "Node3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "Label",
        parent: "Control",
        is_virtual: false,
    },
    ClassInfo {
        name: "Label3D",
        parent: "GeometryInstance3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "Light2D",
        parent: "Node2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "Light3D",
        parent: "VisualInstance3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "Line2D",
        parent: "Node2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "LineEdit",
        parent: "Control",
        is_virtual: false,
    },
    ClassInfo {
        name: "LinkButton",
        parent: "BaseButton",
        is_virtual: false,
    },
    ClassInfo {
        name: "MainLoop",
        parent: "Object",
        is_virtual: false,
    },
    ClassInfo {
        name: "MarginContainer",
        parent: "Container",
        is_virtual: false,
    },
    ClassInfo {
        name: "Material",
        parent: "Resource",
        is_virtual: false,
    },
    ClassInfo {
        name: "MenuBar",
        parent: "Control",
        is_virtual: false,
    },
    ClassInfo {
        name: "MenuButton",
        parent: "Button",
        is_virtual: false,
    },
    ClassInfo {
        name: "Mesh",
        parent: "Resource",
        is_virtual: false,
    },
    ClassInfo {
        name: "MeshInstance2D",
        parent: "Node2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "MeshInstance3D",
        parent: "GeometryInstance3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "MeshLibrary",
        parent: "Resource",
        is_virtual: false,
    },
    ClassInfo {
        name: "MultiMeshInstance2D",
        parent: "Node2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "MultiMeshInstance3D",
        parent: "GeometryInstance3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "NavigationAgent2D",
        parent: "Node",
        is_virtual: false,
    },
    ClassInfo {
        name: "NavigationAgent3D",
        parent: "Node",
        is_virtual: false,
    },
    ClassInfo {
        name: "NavigationRegion2D",
        parent: "Node2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "NavigationRegion3D",
        parent: "Node3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "NinePatchRect",
        parent: "Control",
        is_virtual: false,
    },
    ClassInfo {
        name: "Node",
        parent: "Object",
        is_virtual: false,
    },
    ClassInfo {
        name: "Node2D",
        parent: "CanvasItem",
        is_virtual: false,
    },
    ClassInfo {
        name: "Node3D",
        parent: "Node",
        is_virtual: false,
    },
    ClassInfo {
        name: "Object",
        parent: "",
        is_virtual: false,
    },
    ClassInfo {
        name: "OccluderInstance3D",
        parent: "Node3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "OmniLight3D",
        parent: "Light3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "OptionButton",
        parent: "Button",
        is_virtual: false,
    },
    ClassInfo {
        name: "PackedScene",
        parent: "Resource",
        is_virtual: false,
    },
    ClassInfo {
        name: "Panel",
        parent: "Control",
        is_virtual: false,
    },
    ClassInfo {
        name: "PanelContainer",
        parent: "Container",
        is_virtual: false,
    },
    ClassInfo {
        name: "ParallaxBackground",
        parent: "CanvasLayer",
        is_virtual: false,
    },
    ClassInfo {
        name: "ParallaxLayer",
        parent: "Node2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "Path2D",
        parent: "Node2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "Path3D",
        parent: "Node3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "PathFollow2D",
        parent: "Node2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "PathFollow3D",
        parent: "Node3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "PhysicsBody2D",
        parent: "CollisionObject2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "PhysicsBody3D",
        parent: "CollisionObject3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "PinJoint2D",
        parent: "Joint2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "PinJoint3D",
        parent: "Joint3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "PlaneMesh",
        parent: "PrimitiveMesh",
        is_virtual: false,
    },
    ClassInfo {
        name: "PointLight2D",
        parent: "Light2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "Polygon2D",
        parent: "Node2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "Popup",
        parent: "Window",
        is_virtual: false,
    },
    ClassInfo {
        name: "PopupMenu",
        parent: "Popup",
        is_virtual: false,
    },
    ClassInfo {
        name: "PrimitiveMesh",
        parent: "Mesh",
        is_virtual: false,
    },
    ClassInfo {
        name: "ProgressBar",
        parent: "Range",
        is_virtual: false,
    },
    ClassInfo {
        name: "Range",
        parent: "Control",
        is_virtual: false,
    },
    ClassInfo {
        name: "RayCast2D",
        parent: "Node2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "RayCast3D",
        parent: "Node3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "RectangleShape2D",
        parent: "Shape2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "RefCounted",
        parent: "Object",
        is_virtual: false,
    },
    ClassInfo {
        name: "RenderingServer",
        parent: "Object",
        is_virtual: false,
    },
    ClassInfo {
        name: "Resource",
        parent: "RefCounted",
        is_virtual: false,
    },
    ClassInfo {
        name: "RichTextLabel",
        parent: "Control",
        is_virtual: false,
    },
    ClassInfo {
        name: "RigidBody2D",
        parent: "PhysicsBody2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "RigidBody3D",
        parent: "PhysicsBody3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "SceneTree",
        parent: "MainLoop",
        is_virtual: false,
    },
    ClassInfo {
        name: "ScrollBar",
        parent: "Range",
        is_virtual: false,
    },
    ClassInfo {
        name: "ScrollContainer",
        parent: "Container",
        is_virtual: false,
    },
    ClassInfo {
        name: "SegmentShape2D",
        parent: "Shape2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "Separator",
        parent: "Control",
        is_virtual: false,
    },
    ClassInfo {
        name: "Shader",
        parent: "Resource",
        is_virtual: false,
    },
    ClassInfo {
        name: "ShaderMaterial",
        parent: "Material",
        is_virtual: false,
    },
    ClassInfo {
        name: "Shape2D",
        parent: "Resource",
        is_virtual: false,
    },
    ClassInfo {
        name: "Shape3D",
        parent: "Resource",
        is_virtual: false,
    },
    ClassInfo {
        name: "Skeleton2D",
        parent: "Node2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "Skeleton3D",
        parent: "Node3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "Slider",
        parent: "Range",
        is_virtual: false,
    },
    ClassInfo {
        name: "SphereMesh",
        parent: "PrimitiveMesh",
        is_virtual: false,
    },
    ClassInfo {
        name: "SphereShape3D",
        parent: "Shape3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "SpinBox",
        parent: "Range",
        is_virtual: false,
    },
    ClassInfo {
        name: "SplitContainer",
        parent: "Container",
        is_virtual: false,
    },
    ClassInfo {
        name: "SpotLight3D",
        parent: "Light3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "Sprite2D",
        parent: "Node2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "Sprite3D",
        parent: "SpriteBase3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "SpriteBase3D",
        parent: "GeometryInstance3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "StandardMaterial3D",
        parent: "BaseMaterial3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "StaticBody2D",
        parent: "PhysicsBody2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "StaticBody3D",
        parent: "PhysicsBody3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "StyleBox",
        parent: "Resource",
        is_virtual: false,
    },
    ClassInfo {
        name: "StyleBoxEmpty",
        parent: "StyleBox",
        is_virtual: false,
    },
    ClassInfo {
        name: "StyleBoxFlat",
        parent: "StyleBox",
        is_virtual: false,
    },
    ClassInfo {
        name: "StyleBoxLine",
        parent: "StyleBox",
        is_virtual: false,
    },
    ClassInfo {
        name: "StyleBoxTexture",
        parent: "StyleBox",
        is_virtual: false,
    },
    ClassInfo {
        name: "SubViewport",
        parent: "Viewport",
        is_virtual: false,
    },
    ClassInfo {
        name: "SubViewportContainer",
        parent: "Container",
        is_virtual: false,
    },
    ClassInfo {
        name: "TabBar",
        parent: "Control",
        is_virtual: false,
    },
    ClassInfo {
        name: "TabContainer",
        parent: "Container",
        is_virtual: false,
    },
    ClassInfo {
        name: "TextEdit",
        parent: "Control",
        is_virtual: false,
    },
    ClassInfo {
        name: "Texture",
        parent: "Resource",
        is_virtual: false,
    },
    ClassInfo {
        name: "Texture2D",
        parent: "Texture",
        is_virtual: false,
    },
    ClassInfo {
        name: "TextureButton",
        parent: "BaseButton",
        is_virtual: false,
    },
    ClassInfo {
        name: "TextureProgressBar",
        parent: "Range",
        is_virtual: false,
    },
    ClassInfo {
        name: "TextureRect",
        parent: "Control",
        is_virtual: false,
    },
    ClassInfo {
        name: "Theme",
        parent: "Resource",
        is_virtual: false,
    },
    ClassInfo {
        name: "TileMap",
        parent: "Node2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "TileMapLayer",
        parent: "Node2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "Timer",
        parent: "Node",
        is_virtual: false,
    },
    ClassInfo {
        name: "Tree",
        parent: "Control",
        is_virtual: false,
    },
    ClassInfo {
        name: "Tween",
        parent: "RefCounted",
        is_virtual: false,
    },
    ClassInfo {
        name: "VBoxContainer",
        parent: "BoxContainer",
        is_virtual: false,
    },
    ClassInfo {
        name: "VFlowContainer",
        parent: "FlowContainer",
        is_virtual: false,
    },
    ClassInfo {
        name: "VScrollBar",
        parent: "ScrollBar",
        is_virtual: false,
    },
    ClassInfo {
        name: "VSeparator",
        parent: "Separator",
        is_virtual: false,
    },
    ClassInfo {
        name: "VSlider",
        parent: "Slider",
        is_virtual: false,
    },
    ClassInfo {
        name: "VSplitContainer",
        parent: "SplitContainer",
        is_virtual: false,
    },
    ClassInfo {
        name: "Viewport",
        parent: "Node",
        is_virtual: false,
    },
    ClassInfo {
        name: "VisibleOnScreenNotifier2D",
        parent: "Node2D",
        is_virtual: false,
    },
    ClassInfo {
        name: "VisibleOnScreenNotifier3D",
        parent: "VisualInstance3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "VisualInstance3D",
        parent: "Node3D",
        is_virtual: false,
    },
    ClassInfo {
        name: "VisualShaderNodeCustom",
        parent: "Resource",
        is_virtual: false,
    },
    ClassInfo {
        name: "Window",
        parent: "Viewport",
        is_virtual: false,
    },
    ClassInfo {
        name: "WorldEnvironment",
        parent: "Node",
        is_virtual: false,
    },
];

/// "ClassName.CONSTANT_NAME" -> type string. Sorted.
pub static CONSTANTS: &[(&str, &str)] = &[
    ("@GlobalScope.ERR_ALREADY_EXISTS", "int"),
    ("@GlobalScope.ERR_ALREADY_IN_USE", "int"),
    ("@GlobalScope.ERR_BUG", "int"),
    ("@GlobalScope.ERR_BUSY", "int"),
    ("@GlobalScope.ERR_CANT_ACQUIRE_RESOURCE", "int"),
    ("@GlobalScope.ERR_CANT_CONNECT", "int"),
    ("@GlobalScope.ERR_CANT_CREATE", "int"),
    ("@GlobalScope.ERR_CANT_FORK", "int"),
    ("@GlobalScope.ERR_CANT_OPEN", "int"),
    ("@GlobalScope.ERR_CANT_RESOLVE", "int"),
    ("@GlobalScope.ERR_COMPILATION_FAILED", "int"),
    ("@GlobalScope.ERR_CONNECTION_ERROR", "int"),
    ("@GlobalScope.ERR_CYCLIC_LINK", "int"),
    ("@GlobalScope.ERR_DATABASE_CANT_READ", "int"),
    ("@GlobalScope.ERR_DATABASE_CANT_WRITE", "int"),
    ("@GlobalScope.ERR_DOES_NOT_EXIST", "int"),
    ("@GlobalScope.ERR_DUPLICATE_SYMBOL", "int"),
    ("@GlobalScope.ERR_FILE_ALREADY_IN_USE", "int"),
    ("@GlobalScope.ERR_FILE_BAD_DRIVE", "int"),
    ("@GlobalScope.ERR_FILE_BAD_PATH", "int"),
    ("@GlobalScope.ERR_FILE_CANT_OPEN", "int"),
    ("@GlobalScope.ERR_FILE_CANT_READ", "int"),
    ("@GlobalScope.ERR_FILE_CANT_WRITE", "int"),
    ("@GlobalScope.ERR_FILE_CORRUPT", "int"),
    ("@GlobalScope.ERR_FILE_EOF", "int"),
    ("@GlobalScope.ERR_FILE_MISSING_DEPENDENCIES", "int"),
    ("@GlobalScope.ERR_FILE_NOT_FOUND", "int"),
    ("@GlobalScope.ERR_FILE_NO_PERMISSION", "int"),
    ("@GlobalScope.ERR_FILE_UNRECOGNIZED", "int"),
    ("@GlobalScope.ERR_HELP", "int"),
    ("@GlobalScope.ERR_INVALID_DATA", "int"),
    ("@GlobalScope.ERR_INVALID_DECLARATION", "int"),
    ("@GlobalScope.ERR_INVALID_PARAMETER", "int"),
    ("@GlobalScope.ERR_LINK_FAILED", "int"),
    ("@GlobalScope.ERR_LOCKED", "int"),
    ("@GlobalScope.ERR_METHOD_NOT_FOUND", "int"),
    ("@GlobalScope.ERR_MIDI_INVALID_STATUS", "int"),
    ("@GlobalScope.ERR_OUT_OF_MEMORY", "int"),
    ("@GlobalScope.ERR_PARAMETER_RANGE_ERROR", "int"),
    ("@GlobalScope.ERR_PARSE_ERROR", "int"),
    ("@GlobalScope.ERR_PRINTER_ON_FIRE", "int"),
    ("@GlobalScope.ERR_QUERY_FAILED", "int"),
    ("@GlobalScope.ERR_SCRIPT_FAILED", "int"),
    ("@GlobalScope.ERR_SKIP", "int"),
    ("@GlobalScope.ERR_TIMEOUT", "int"),
    ("@GlobalScope.ERR_UNAUTHORIZED", "int"),
    ("@GlobalScope.ERR_UNAVAILABLE", "int"),
    ("@GlobalScope.ERR_UNCONFIGURED", "int"),
    ("@GlobalScope.FAILED", "int"),
    ("@GlobalScope.INF", "float"),
    ("@GlobalScope.JOY_AXIS_INVALID", "int"),
    ("@GlobalScope.JOY_AXIS_LEFT_X", "int"),
    ("@GlobalScope.JOY_AXIS_LEFT_Y", "int"),
    ("@GlobalScope.JOY_AXIS_RIGHT_X", "int"),
    ("@GlobalScope.JOY_AXIS_RIGHT_Y", "int"),
    ("@GlobalScope.JOY_AXIS_TRIGGER_LEFT", "int"),
    ("@GlobalScope.JOY_AXIS_TRIGGER_RIGHT", "int"),
    ("@GlobalScope.JOY_BUTTON_A", "int"),
    ("@GlobalScope.JOY_BUTTON_B", "int"),
    ("@GlobalScope.JOY_BUTTON_BACK", "int"),
    ("@GlobalScope.JOY_BUTTON_DPAD_DOWN", "int"),
    ("@GlobalScope.JOY_BUTTON_DPAD_LEFT", "int"),
    ("@GlobalScope.JOY_BUTTON_DPAD_RIGHT", "int"),
    ("@GlobalScope.JOY_BUTTON_DPAD_UP", "int"),
    ("@GlobalScope.JOY_BUTTON_GUIDE", "int"),
    ("@GlobalScope.JOY_BUTTON_INVALID", "int"),
    ("@GlobalScope.JOY_BUTTON_LEFT_SHOULDER", "int"),
    ("@GlobalScope.JOY_BUTTON_LEFT_STICK", "int"),
    ("@GlobalScope.JOY_BUTTON_MISC1", "int"),
    ("@GlobalScope.JOY_BUTTON_PADDLE1", "int"),
    ("@GlobalScope.JOY_BUTTON_PADDLE2", "int"),
    ("@GlobalScope.JOY_BUTTON_PADDLE3", "int"),
    ("@GlobalScope.JOY_BUTTON_PADDLE4", "int"),
    ("@GlobalScope.JOY_BUTTON_RIGHT_SHOULDER", "int"),
    ("@GlobalScope.JOY_BUTTON_RIGHT_STICK", "int"),
    ("@GlobalScope.JOY_BUTTON_START", "int"),
    ("@GlobalScope.JOY_BUTTON_TOUCHPAD", "int"),
    ("@GlobalScope.JOY_BUTTON_X", "int"),
    ("@GlobalScope.JOY_BUTTON_Y", "int"),
    ("@GlobalScope.KEY_0", "int"),
    ("@GlobalScope.KEY_1", "int"),
    ("@GlobalScope.KEY_2", "int"),
    ("@GlobalScope.KEY_3", "int"),
    ("@GlobalScope.KEY_4", "int"),
    ("@GlobalScope.KEY_5", "int"),
    ("@GlobalScope.KEY_6", "int"),
    ("@GlobalScope.KEY_7", "int"),
    ("@GlobalScope.KEY_8", "int"),
    ("@GlobalScope.KEY_9", "int"),
    ("@GlobalScope.KEY_A", "int"),
    ("@GlobalScope.KEY_ALT", "int"),
    ("@GlobalScope.KEY_B", "int"),
    ("@GlobalScope.KEY_BACKSPACE", "int"),
    ("@GlobalScope.KEY_C", "int"),
    ("@GlobalScope.KEY_CAPSLOCK", "int"),
    ("@GlobalScope.KEY_CTRL", "int"),
    ("@GlobalScope.KEY_D", "int"),
    ("@GlobalScope.KEY_DELETE", "int"),
    ("@GlobalScope.KEY_DOWN", "int"),
    ("@GlobalScope.KEY_E", "int"),
    ("@GlobalScope.KEY_END", "int"),
    ("@GlobalScope.KEY_ENTER", "int"),
    ("@GlobalScope.KEY_ESCAPE", "int"),
    ("@GlobalScope.KEY_F", "int"),
    ("@GlobalScope.KEY_F1", "int"),
    ("@GlobalScope.KEY_F10", "int"),
    ("@GlobalScope.KEY_F11", "int"),
    ("@GlobalScope.KEY_F12", "int"),
    ("@GlobalScope.KEY_F2", "int"),
    ("@GlobalScope.KEY_F3", "int"),
    ("@GlobalScope.KEY_F4", "int"),
    ("@GlobalScope.KEY_F5", "int"),
    ("@GlobalScope.KEY_F6", "int"),
    ("@GlobalScope.KEY_F7", "int"),
    ("@GlobalScope.KEY_F8", "int"),
    ("@GlobalScope.KEY_F9", "int"),
    ("@GlobalScope.KEY_G", "int"),
    ("@GlobalScope.KEY_H", "int"),
    ("@GlobalScope.KEY_HOME", "int"),
    ("@GlobalScope.KEY_I", "int"),
    ("@GlobalScope.KEY_INSERT", "int"),
    ("@GlobalScope.KEY_J", "int"),
    ("@GlobalScope.KEY_K", "int"),
    ("@GlobalScope.KEY_KP_0", "int"),
    ("@GlobalScope.KEY_KP_1", "int"),
    ("@GlobalScope.KEY_KP_2", "int"),
    ("@GlobalScope.KEY_KP_3", "int"),
    ("@GlobalScope.KEY_KP_4", "int"),
    ("@GlobalScope.KEY_KP_5", "int"),
    ("@GlobalScope.KEY_KP_6", "int"),
    ("@GlobalScope.KEY_KP_7", "int"),
    ("@GlobalScope.KEY_KP_8", "int"),
    ("@GlobalScope.KEY_KP_9", "int"),
    ("@GlobalScope.KEY_KP_ADD", "int"),
    ("@GlobalScope.KEY_KP_ENTER", "int"),
    ("@GlobalScope.KEY_KP_MULTIPLY", "int"),
    ("@GlobalScope.KEY_KP_PERIOD", "int"),
    ("@GlobalScope.KEY_KP_SUBTRACT", "int"),
    ("@GlobalScope.KEY_L", "int"),
    ("@GlobalScope.KEY_LEFT", "int"),
    ("@GlobalScope.KEY_M", "int"),
    ("@GlobalScope.KEY_META", "int"),
    ("@GlobalScope.KEY_N", "int"),
    ("@GlobalScope.KEY_NONE", "int"),
    ("@GlobalScope.KEY_O", "int"),
    ("@GlobalScope.KEY_P", "int"),
    ("@GlobalScope.KEY_PAGEDOWN", "int"),
    ("@GlobalScope.KEY_PAGEUP", "int"),
    ("@GlobalScope.KEY_Q", "int"),
    ("@GlobalScope.KEY_R", "int"),
    ("@GlobalScope.KEY_RIGHT", "int"),
    ("@GlobalScope.KEY_S", "int"),
    ("@GlobalScope.KEY_SHIFT", "int"),
    ("@GlobalScope.KEY_SPACE", "int"),
    ("@GlobalScope.KEY_T", "int"),
    ("@GlobalScope.KEY_TAB", "int"),
    ("@GlobalScope.KEY_U", "int"),
    ("@GlobalScope.KEY_UP", "int"),
    ("@GlobalScope.KEY_V", "int"),
    ("@GlobalScope.KEY_W", "int"),
    ("@GlobalScope.KEY_X", "int"),
    ("@GlobalScope.KEY_Y", "int"),
    ("@GlobalScope.KEY_Z", "int"),
    ("@GlobalScope.MOUSE_BUTTON_LEFT", "int"),
    ("@GlobalScope.MOUSE_BUTTON_MASK_LEFT", "int"),
    ("@GlobalScope.MOUSE_BUTTON_MASK_MIDDLE", "int"),
    ("@GlobalScope.MOUSE_BUTTON_MASK_RIGHT", "int"),
    ("@GlobalScope.MOUSE_BUTTON_MIDDLE", "int"),
    ("@GlobalScope.MOUSE_BUTTON_NONE", "int"),
    ("@GlobalScope.MOUSE_BUTTON_RIGHT", "int"),
    ("@GlobalScope.MOUSE_BUTTON_WHEEL_DOWN", "int"),
    ("@GlobalScope.MOUSE_BUTTON_WHEEL_LEFT", "int"),
    ("@GlobalScope.MOUSE_BUTTON_WHEEL_RIGHT", "int"),
    ("@GlobalScope.MOUSE_BUTTON_WHEEL_UP", "int"),
    ("@GlobalScope.MOUSE_BUTTON_XBUTTON1", "int"),
    ("@GlobalScope.MOUSE_BUTTON_XBUTTON2", "int"),
    ("@GlobalScope.NAN", "float"),
    ("@GlobalScope.OK", "int"),
    ("@GlobalScope.PI", "float"),
    ("@GlobalScope.TAU", "float"),
    ("@GlobalScope.TYPE_AABB", "int"),
    ("@GlobalScope.TYPE_ARRAY", "int"),
    ("@GlobalScope.TYPE_BASIS", "int"),
    ("@GlobalScope.TYPE_BOOL", "int"),
    ("@GlobalScope.TYPE_CALLABLE", "int"),
    ("@GlobalScope.TYPE_COLOR", "int"),
    ("@GlobalScope.TYPE_DICTIONARY", "int"),
    ("@GlobalScope.TYPE_FLOAT", "int"),
    ("@GlobalScope.TYPE_INT", "int"),
    ("@GlobalScope.TYPE_MAX", "int"),
    ("@GlobalScope.TYPE_NIL", "int"),
    ("@GlobalScope.TYPE_NODE_PATH", "int"),
    ("@GlobalScope.TYPE_OBJECT", "int"),
    ("@GlobalScope.TYPE_PACKED_BYTE_ARRAY", "int"),
    ("@GlobalScope.TYPE_PACKED_COLOR_ARRAY", "int"),
    ("@GlobalScope.TYPE_PACKED_FLOAT32_ARRAY", "int"),
    ("@GlobalScope.TYPE_PACKED_FLOAT64_ARRAY", "int"),
    ("@GlobalScope.TYPE_PACKED_INT32_ARRAY", "int"),
    ("@GlobalScope.TYPE_PACKED_INT64_ARRAY", "int"),
    ("@GlobalScope.TYPE_PACKED_STRING_ARRAY", "int"),
    ("@GlobalScope.TYPE_PACKED_VECTOR2_ARRAY", "int"),
    ("@GlobalScope.TYPE_PACKED_VECTOR3_ARRAY", "int"),
    ("@GlobalScope.TYPE_PACKED_VECTOR4_ARRAY", "int"),
    ("@GlobalScope.TYPE_PLANE", "int"),
    ("@GlobalScope.TYPE_PROJECTION", "int"),
    ("@GlobalScope.TYPE_QUATERNION", "int"),
    ("@GlobalScope.TYPE_RECT2", "int"),
    ("@GlobalScope.TYPE_RECT2I", "int"),
    ("@GlobalScope.TYPE_RID", "int"),
    ("@GlobalScope.TYPE_SIGNAL", "int"),
    ("@GlobalScope.TYPE_STRING", "int"),
    ("@GlobalScope.TYPE_STRING_NAME", "int"),
    ("@GlobalScope.TYPE_TRANSFORM2D", "int"),
    ("@GlobalScope.TYPE_TRANSFORM3D", "int"),
    ("@GlobalScope.TYPE_VECTOR2", "int"),
    ("@GlobalScope.TYPE_VECTOR2I", "int"),
    ("@GlobalScope.TYPE_VECTOR3", "int"),
    ("@GlobalScope.TYPE_VECTOR3I", "int"),
    ("@GlobalScope.TYPE_VECTOR4", "int"),
    ("@GlobalScope.TYPE_VECTOR4I", "int"),
    ("Node.NOTIFICATION_CHILD_ORDER_CHANGED", "int"),
    ("Node.NOTIFICATION_DISABLED", "int"),
    ("Node.NOTIFICATION_DRAG_BEGIN", "int"),
    ("Node.NOTIFICATION_DRAG_END", "int"),
    ("Node.NOTIFICATION_EDITOR_POST_SAVE", "int"),
    ("Node.NOTIFICATION_EDITOR_PRE_SAVE", "int"),
    ("Node.NOTIFICATION_ENABLED", "int"),
    ("Node.NOTIFICATION_ENTER_TREE", "int"),
    ("Node.NOTIFICATION_EXIT_TREE", "int"),
    ("Node.NOTIFICATION_MOVED_IN_PARENT", "int"),
    ("Node.NOTIFICATION_PARENTED", "int"),
    ("Node.NOTIFICATION_PATH_RENAMED", "int"),
    ("Node.NOTIFICATION_PAUSED", "int"),
    ("Node.NOTIFICATION_PHYSICS_PROCESS", "int"),
    ("Node.NOTIFICATION_POST_ENTER_TREE", "int"),
    ("Node.NOTIFICATION_PROCESS", "int"),
    ("Node.NOTIFICATION_READY", "int"),
    ("Node.NOTIFICATION_RESET_PHYSICS_INTERPOLATION", "int"),
    ("Node.NOTIFICATION_SCENE_INSTANTIATED", "int"),
    ("Node.NOTIFICATION_TRANSLATION_CHANGED", "int"),
    ("Node.NOTIFICATION_UNPARENTED", "int"),
    ("Node.NOTIFICATION_UNPAUSED", "int"),
    ("Node.NOTIFICATION_WM_WINDOW_FOCUS_IN", "int"),
    ("Node.NOTIFICATION_WM_WINDOW_FOCUS_OUT", "int"),
    ("Object.NOTIFICATION_POSTINITIALIZE", "int"),
    ("Object.NOTIFICATION_PREDELETE", "int"),
];

/// "ClassName.ENUM_MEMBER" -> "EnumName". Sorted.
pub static ENUM_MEMBERS: &[(&str, &str)] = &[
    (
        "BaseMaterial3D.ALPHA_ANTIALIASING_ALPHA_TO_COVERAGE",
        "AlphaAntiAliasing",
    ),
    (
        "BaseMaterial3D.ALPHA_ANTIALIASING_ALPHA_TO_COVERAGE_AND_TO_ONE",
        "AlphaAntiAliasing",
    ),
    ("BaseMaterial3D.ALPHA_ANTIALIASING_OFF", "AlphaAntiAliasing"),
    ("BaseMaterial3D.BLEND_MODE_ADD", "BlendMode"),
    ("BaseMaterial3D.BLEND_MODE_MIX", "BlendMode"),
    ("BaseMaterial3D.BLEND_MODE_MUL", "BlendMode"),
    ("BaseMaterial3D.BLEND_MODE_PREMULT_ALPHA", "BlendMode"),
    ("BaseMaterial3D.BLEND_MODE_SUB", "BlendMode"),
    ("BaseMaterial3D.CULL_BACK", "CullMode"),
    ("BaseMaterial3D.CULL_DISABLED", "CullMode"),
    ("BaseMaterial3D.CULL_FRONT", "CullMode"),
    ("BaseMaterial3D.TRANSPARENCY_ALPHA", "Transparency"),
    (
        "BaseMaterial3D.TRANSPARENCY_ALPHA_DEPTH_PRE_PASS",
        "Transparency",
    ),
    ("BaseMaterial3D.TRANSPARENCY_ALPHA_HASH", "Transparency"),
    ("BaseMaterial3D.TRANSPARENCY_ALPHA_SCISSOR", "Transparency"),
    ("BaseMaterial3D.TRANSPARENCY_DISABLED", "Transparency"),
    ("BaseMaterial3D.TRANSPARENCY_MAX", "Transparency"),
    ("CanvasItem.TEXTURE_FILTER_INHERIT", "TextureFilter"),
    ("CanvasItem.TEXTURE_FILTER_LINEAR", "TextureFilter"),
    (
        "CanvasItem.TEXTURE_FILTER_LINEAR_WITH_MIPMAPS",
        "TextureFilter",
    ),
    ("CanvasItem.TEXTURE_FILTER_NEAREST", "TextureFilter"),
    (
        "CanvasItem.TEXTURE_FILTER_NEAREST_WITH_MIPMAPS",
        "TextureFilter",
    ),
    ("CanvasItem.TEXTURE_REPEAT_DISABLED", "TextureRepeat"),
    ("CanvasItem.TEXTURE_REPEAT_ENABLED", "TextureRepeat"),
    ("CanvasItem.TEXTURE_REPEAT_INHERIT", "TextureRepeat"),
    ("CanvasItem.TEXTURE_REPEAT_MIRROR", "TextureRepeat"),
    ("CharacterBody2D.MOTION_MODE_FLOATING", "MotionMode"),
    ("CharacterBody2D.MOTION_MODE_GROUNDED", "MotionMode"),
    (
        "CharacterBody2D.PLATFORM_ON_LEAVE_ADD_UPWARD_VELOCITY",
        "PlatformOnLeave",
    ),
    (
        "CharacterBody2D.PLATFORM_ON_LEAVE_ADD_VELOCITY",
        "PlatformOnLeave",
    ),
    (
        "CharacterBody2D.PLATFORM_ON_LEAVE_DO_NOTHING",
        "PlatformOnLeave",
    ),
    ("CharacterBody3D.MOTION_MODE_FLOATING", "MotionMode"),
    ("CharacterBody3D.MOTION_MODE_GROUNDED", "MotionMode"),
    (
        "CharacterBody3D.PLATFORM_ON_LEAVE_ADD_UPWARD_VELOCITY",
        "PlatformOnLeave",
    ),
    (
        "CharacterBody3D.PLATFORM_ON_LEAVE_ADD_VELOCITY",
        "PlatformOnLeave",
    ),
    (
        "CharacterBody3D.PLATFORM_ON_LEAVE_DO_NOTHING",
        "PlatformOnLeave",
    ),
    ("Control.ANCHOR_BEGIN", "LayoutPreset"),
    ("Control.ANCHOR_END", "LayoutPreset"),
    ("Control.CURSOR_ARROW", "CursorShape"),
    ("Control.CURSOR_BDIAGSIZE", "CursorShape"),
    ("Control.CURSOR_BUSY", "CursorShape"),
    ("Control.CURSOR_CAN_DROP", "CursorShape"),
    ("Control.CURSOR_CROSS", "CursorShape"),
    ("Control.CURSOR_DRAG", "CursorShape"),
    ("Control.CURSOR_FDIAGSIZE", "CursorShape"),
    ("Control.CURSOR_FORBIDDEN", "CursorShape"),
    ("Control.CURSOR_HSIZE", "CursorShape"),
    ("Control.CURSOR_HSPLIT", "CursorShape"),
    ("Control.CURSOR_IBEAM", "CursorShape"),
    ("Control.CURSOR_MOVE", "CursorShape"),
    ("Control.CURSOR_POINTING_HAND", "CursorShape"),
    ("Control.CURSOR_VSIZE", "CursorShape"),
    ("Control.CURSOR_VSPLIT", "CursorShape"),
    ("Control.CURSOR_WAIT", "CursorShape"),
    ("Control.FOCUS_ALL", "FocusMode"),
    ("Control.FOCUS_CLICK", "FocusMode"),
    ("Control.FOCUS_NONE", "FocusMode"),
    ("Control.GROW_DIRECTION_BEGIN", "GrowDirection"),
    ("Control.GROW_DIRECTION_BOTH", "GrowDirection"),
    ("Control.GROW_DIRECTION_END", "GrowDirection"),
    ("Control.LAYOUT_DIRECTION_INHERITED", "LayoutDirection"),
    ("Control.LAYOUT_DIRECTION_LTR", "LayoutDirection"),
    ("Control.LAYOUT_DIRECTION_RTL", "LayoutDirection"),
    ("Control.MOUSE_FILTER_IGNORE", "MouseFilter"),
    ("Control.MOUSE_FILTER_PASS", "MouseFilter"),
    ("Control.MOUSE_FILTER_STOP", "MouseFilter"),
    ("Control.PRESET_BOTTOM_LEFT", "LayoutPreset"),
    ("Control.PRESET_BOTTOM_RIGHT", "LayoutPreset"),
    ("Control.PRESET_BOTTOM_WIDE", "LayoutPreset"),
    ("Control.PRESET_CENTER", "LayoutPreset"),
    ("Control.PRESET_CENTER_BOTTOM", "LayoutPreset"),
    ("Control.PRESET_CENTER_LEFT", "LayoutPreset"),
    ("Control.PRESET_CENTER_RIGHT", "LayoutPreset"),
    ("Control.PRESET_CENTER_TOP", "LayoutPreset"),
    ("Control.PRESET_FULL_RECT", "LayoutPreset"),
    ("Control.PRESET_HCENTER_WIDE", "LayoutPreset"),
    ("Control.PRESET_LEFT_WIDE", "LayoutPreset"),
    ("Control.PRESET_RIGHT_WIDE", "LayoutPreset"),
    ("Control.PRESET_TOP_LEFT", "LayoutPreset"),
    ("Control.PRESET_TOP_RIGHT", "LayoutPreset"),
    ("Control.PRESET_TOP_WIDE", "LayoutPreset"),
    ("Control.PRESET_VCENTER_WIDE", "LayoutPreset"),
    ("Control.SIZE_EXPAND", "SizeFlags"),
    ("Control.SIZE_EXPAND_FILL", "SizeFlags"),
    ("Control.SIZE_FILL", "SizeFlags"),
    ("Control.SIZE_SHRINK_BEGIN", "SizeFlags"),
    ("Control.SIZE_SHRINK_CENTER", "SizeFlags"),
    ("Control.SIZE_SHRINK_END", "SizeFlags"),
    ("Environment.AMBIENT_SOURCE_BG", "AmbientSource"),
    ("Environment.AMBIENT_SOURCE_COLOR", "AmbientSource"),
    ("Environment.AMBIENT_SOURCE_DISABLED", "AmbientSource"),
    ("Environment.AMBIENT_SOURCE_SKY", "AmbientSource"),
    ("Environment.BG_CAMERA_FEED", "BGMode"),
    ("Environment.BG_CANVAS", "BGMode"),
    ("Environment.BG_CLEAR_COLOR", "BGMode"),
    ("Environment.BG_COLOR", "BGMode"),
    ("Environment.BG_KEEP", "BGMode"),
    ("Environment.BG_MAX", "BGMode"),
    ("Environment.BG_SKY", "BGMode"),
    ("Environment.FOG_MODE_DEPTH", "FogMode"),
    ("Environment.FOG_MODE_EXPONENTIAL", "FogMode"),
    ("Environment.GLOW_BLEND_MODE_ADDITIVE", "GlowBlendMode"),
    ("Environment.GLOW_BLEND_MODE_MIX", "GlowBlendMode"),
    ("Environment.GLOW_BLEND_MODE_REPLACE", "GlowBlendMode"),
    ("Environment.GLOW_BLEND_MODE_SOFTLIGHT", "GlowBlendMode"),
    ("Environment.REFLECTION_SOURCE_BG", "ReflectionSource"),
    ("Environment.REFLECTION_SOURCE_DISABLED", "ReflectionSource"),
    ("Environment.REFLECTION_SOURCE_SKY", "ReflectionSource"),
    ("Environment.SDFGI_Y_SCALE_100_PERCENT", "SDFGIYScale"),
    ("Environment.SDFGI_Y_SCALE_50_PERCENT", "SDFGIYScale"),
    ("Environment.SDFGI_Y_SCALE_75_PERCENT", "SDFGIYScale"),
    ("Environment.SSAO_BLUR_1x1", "SSAOBlur"),
    ("Environment.SSAO_BLUR_2x2", "SSAOBlur"),
    ("Environment.SSAO_BLUR_3x3", "SSAOBlur"),
    ("Environment.SSAO_BLUR_DISABLED", "SSAOBlur"),
    ("Environment.TONE_MAPPER_ACES", "ToneMapper"),
    ("Environment.TONE_MAPPER_FILMIC", "ToneMapper"),
    ("Environment.TONE_MAPPER_LINEAR", "ToneMapper"),
    ("Environment.TONE_MAPPER_REINHARDT", "ToneMapper"),
    ("Light3D.BAKE_DISABLED", "BakeMode"),
    ("Light3D.BAKE_DYNAMIC", "BakeMode"),
    ("Light3D.BAKE_STATIC", "BakeMode"),
    ("Node.DUPLICATE_GROUPS", "DuplicateFlags"),
    ("Node.DUPLICATE_SCRIPTS", "DuplicateFlags"),
    ("Node.DUPLICATE_SIGNALS", "DuplicateFlags"),
    ("Node.DUPLICATE_USE_INSTANTIATION", "DuplicateFlags"),
    ("Node.INTERNAL_MODE_BACK", "InternalMode"),
    ("Node.INTERNAL_MODE_DISABLED", "InternalMode"),
    ("Node.INTERNAL_MODE_FRONT", "InternalMode"),
    ("Node.PROCESS_MODE_ALWAYS", "ProcessMode"),
    ("Node.PROCESS_MODE_DISABLED", "ProcessMode"),
    ("Node.PROCESS_MODE_INHERIT", "ProcessMode"),
    ("Node.PROCESS_MODE_PAUSABLE", "ProcessMode"),
    ("Node.PROCESS_MODE_WHEN_PAUSED", "ProcessMode"),
    ("Node.PROCESS_THREAD_GROUP_INHERIT", "ProcessThreadGroup"),
    (
        "Node.PROCESS_THREAD_GROUP_MAIN_THREAD",
        "ProcessThreadGroup",
    ),
    ("Node.PROCESS_THREAD_GROUP_SUB_THREAD", "ProcessThreadGroup"),
    ("RigidBody2D.CENTER_OF_MASS_MODE_AUTO", "CenterOfMassMode"),
    ("RigidBody2D.CENTER_OF_MASS_MODE_CUSTOM", "CenterOfMassMode"),
    ("RigidBody2D.FREEZE_MODE_KINEMATIC", "FreezeMode"),
    ("RigidBody2D.FREEZE_MODE_STATIC", "FreezeMode"),
    ("RigidBody3D.CENTER_OF_MASS_MODE_AUTO", "CenterOfMassMode"),
    ("RigidBody3D.CENTER_OF_MASS_MODE_CUSTOM", "CenterOfMassMode"),
    ("RigidBody3D.FREEZE_MODE_KINEMATIC", "FreezeMode"),
    ("RigidBody3D.FREEZE_MODE_STATIC", "FreezeMode"),
    ("Tween.EASE_IN", "EaseType"),
    ("Tween.EASE_IN_OUT", "EaseType"),
    ("Tween.EASE_OUT", "EaseType"),
    ("Tween.EASE_OUT_IN", "EaseType"),
    ("Tween.TRANS_BACK", "TransitionType"),
    ("Tween.TRANS_BOUNCE", "TransitionType"),
    ("Tween.TRANS_CIRC", "TransitionType"),
    ("Tween.TRANS_CUBIC", "TransitionType"),
    ("Tween.TRANS_ELASTIC", "TransitionType"),
    ("Tween.TRANS_EXPO", "TransitionType"),
    ("Tween.TRANS_LINEAR", "TransitionType"),
    ("Tween.TRANS_QUAD", "TransitionType"),
    ("Tween.TRANS_QUART", "TransitionType"),
    ("Tween.TRANS_QUINT", "TransitionType"),
    ("Tween.TRANS_SINE", "TransitionType"),
    ("Tween.TRANS_SPRING", "TransitionType"),
    ("Viewport.DEBUG_DRAW_CLUSTER_DECALS", "DebugDraw"),
    ("Viewport.DEBUG_DRAW_CLUSTER_OMNI_LIGHTS", "DebugDraw"),
    ("Viewport.DEBUG_DRAW_CLUSTER_SPOT_LIGHTS", "DebugDraw"),
    ("Viewport.DEBUG_DRAW_DISABLED", "DebugDraw"),
    ("Viewport.DEBUG_DRAW_WIREFRAME", "DebugDraw"),
    (
        "Viewport.DEFAULT_CANVAS_ITEM_TEXTURE_FILTER_LINEAR",
        "DefaultCanvasItemTextureFilter",
    ),
    (
        "Viewport.DEFAULT_CANVAS_ITEM_TEXTURE_FILTER_LINEAR_WITH_MIPMAPS",
        "DefaultCanvasItemTextureFilter",
    ),
    (
        "Viewport.DEFAULT_CANVAS_ITEM_TEXTURE_FILTER_NEAREST",
        "DefaultCanvasItemTextureFilter",
    ),
    (
        "Viewport.DEFAULT_CANVAS_ITEM_TEXTURE_FILTER_NEAREST_WITH_MIPMAPS",
        "DefaultCanvasItemTextureFilter",
    ),
    ("Viewport.MSAA_2X", "MSAA"),
    ("Viewport.MSAA_4X", "MSAA"),
    ("Viewport.MSAA_8X", "MSAA"),
    ("Viewport.MSAA_DISABLED", "MSAA"),
    ("Viewport.MSAA_MAX", "MSAA"),
    ("Viewport.SCALING_3D_MODE_BILINEAR", "Scaling3DMode"),
    ("Viewport.SCALING_3D_MODE_FSR", "Scaling3DMode"),
    ("Viewport.SCALING_3D_MODE_FSR2", "Scaling3DMode"),
    ("Viewport.SCREEN_SPACE_AA_DISABLED", "ScreenSpaceAA"),
    ("Viewport.SCREEN_SPACE_AA_FXAA", "ScreenSpaceAA"),
    ("Window.MODE_EXCLUSIVE_FULLSCREEN", "Mode"),
    ("Window.MODE_FULLSCREEN", "Mode"),
    ("Window.MODE_MAXIMIZED", "Mode"),
    ("Window.MODE_MINIMIZED", "Mode"),
    ("Window.MODE_WINDOWED", "Mode"),
];

/// "ClassName.method_name" -> return_type. Sorted.
pub static METHODS: &[(&str, &str)] = &[
    ("AnimatedSprite2D.get_sprite_frames", "SpriteFrames"),
    ("AnimatedSprite2D.is_playing", "bool"),
    ("AnimatedSprite2D.pause", "void"),
    ("AnimatedSprite2D.play", "void"),
    ("AnimatedSprite2D.set_sprite_frames", "void"),
    ("AnimatedSprite2D.stop", "void"),
    ("AnimationMixer.get_animation", "Animation"),
    ("AnimationMixer.has_animation", "bool"),
    ("AnimationPlayer.get_assigned_animation", "String"),
    ("AnimationPlayer.get_current_animation", "String"),
    ("AnimationPlayer.get_current_animation_length", "float"),
    ("AnimationPlayer.get_current_animation_position", "float"),
    ("AnimationPlayer.is_playing", "bool"),
    ("AnimationPlayer.pause", "void"),
    ("AnimationPlayer.play", "void"),
    ("AnimationPlayer.play_backwards", "void"),
    ("AnimationPlayer.queue", "void"),
    ("AnimationPlayer.seek", "void"),
    ("AnimationPlayer.stop", "void"),
    ("Area2D.get_overlapping_areas", "Array"),
    ("Area2D.get_overlapping_bodies", "Array"),
    ("Area2D.has_overlapping_areas", "bool"),
    ("Area2D.has_overlapping_bodies", "bool"),
    ("Area3D.get_overlapping_areas", "Array"),
    ("Area3D.get_overlapping_bodies", "Array"),
    ("Area3D.has_overlapping_areas", "bool"),
    ("Area3D.has_overlapping_bodies", "bool"),
    ("AudioStreamPlayer.get_playback_position", "float"),
    ("AudioStreamPlayer.is_playing", "bool"),
    ("AudioStreamPlayer.play", "void"),
    ("AudioStreamPlayer.seek", "void"),
    ("AudioStreamPlayer.stop", "void"),
    ("AudioStreamPlayer2D.get_playback_position", "float"),
    ("AudioStreamPlayer2D.is_playing", "bool"),
    ("AudioStreamPlayer2D.play", "void"),
    ("AudioStreamPlayer2D.seek", "void"),
    ("AudioStreamPlayer2D.stop", "void"),
    ("AudioStreamPlayer3D.get_playback_position", "float"),
    ("AudioStreamPlayer3D.is_playing", "bool"),
    ("AudioStreamPlayer3D.play", "void"),
    ("AudioStreamPlayer3D.seek", "void"),
    ("AudioStreamPlayer3D.stop", "void"),
    ("BaseButton.is_disabled", "bool"),
    ("BaseButton.is_hovered", "bool"),
    ("BaseButton.is_pressed", "bool"),
    ("BaseButton.set_disabled", "void"),
    ("BaseButton.set_pressed", "void"),
    ("Camera2D.get_zoom", "Vector2"),
    ("Camera2D.make_current", "void"),
    ("Camera2D.reset_smoothing", "void"),
    ("Camera2D.set_zoom", "void"),
    ("Camera3D.get_camera_transform", "Transform3D"),
    ("Camera3D.get_fov", "float"),
    ("Camera3D.is_current", "bool"),
    ("Camera3D.make_current", "void"),
    ("Camera3D.project_position", "Vector3"),
    ("Camera3D.project_ray_normal", "Vector3"),
    ("Camera3D.project_ray_origin", "Vector3"),
    ("Camera3D.unproject_position", "Vector2"),
    ("CanvasItem.draw_arc", "void"),
    ("CanvasItem.draw_circle", "void"),
    ("CanvasItem.draw_line", "void"),
    ("CanvasItem.draw_rect", "void"),
    ("CanvasItem.draw_string", "void"),
    ("CanvasItem.draw_texture", "void"),
    ("CanvasItem.get_global_mouse_position", "Vector2"),
    ("CanvasItem.get_global_transform", "Transform2D"),
    ("CanvasItem.get_local_mouse_position", "Vector2"),
    ("CanvasItem.get_viewport_transform", "Transform2D"),
    ("CanvasItem.hide", "void"),
    ("CanvasItem.is_visible", "bool"),
    ("CanvasItem.is_visible_in_tree", "bool"),
    ("CanvasItem.queue_redraw", "void"),
    ("CanvasItem.set_visible", "void"),
    ("CanvasItem.show", "void"),
    ("CharacterBody2D.get_floor_angle", "float"),
    ("CharacterBody2D.get_floor_normal", "Vector2"),
    ("CharacterBody2D.get_last_motion", "Vector2"),
    (
        "CharacterBody2D.get_last_slide_collision",
        "KinematicCollision2D",
    ),
    ("CharacterBody2D.get_platform_velocity", "Vector2"),
    ("CharacterBody2D.get_position_delta", "Vector2"),
    ("CharacterBody2D.get_real_velocity", "Vector2"),
    (
        "CharacterBody2D.get_slide_collision",
        "KinematicCollision2D",
    ),
    ("CharacterBody2D.get_slide_collision_count", "int"),
    ("CharacterBody2D.get_wall_normal", "Vector2"),
    ("CharacterBody2D.is_on_ceiling", "bool"),
    ("CharacterBody2D.is_on_floor", "bool"),
    ("CharacterBody2D.is_on_wall", "bool"),
    ("CharacterBody2D.move_and_slide", "bool"),
    ("CharacterBody3D.get_floor_angle", "float"),
    ("CharacterBody3D.get_floor_normal", "Vector3"),
    ("CharacterBody3D.get_last_motion", "Vector3"),
    (
        "CharacterBody3D.get_last_slide_collision",
        "KinematicCollision3D",
    ),
    ("CharacterBody3D.get_platform_angular_velocity", "Vector3"),
    ("CharacterBody3D.get_platform_velocity", "Vector3"),
    ("CharacterBody3D.get_position_delta", "Vector3"),
    ("CharacterBody3D.get_real_velocity", "Vector3"),
    (
        "CharacterBody3D.get_slide_collision",
        "KinematicCollision3D",
    ),
    ("CharacterBody3D.get_slide_collision_count", "int"),
    ("CharacterBody3D.get_wall_normal", "Vector3"),
    ("CharacterBody3D.is_on_ceiling", "bool"),
    ("CharacterBody3D.is_on_floor", "bool"),
    ("CharacterBody3D.is_on_wall", "bool"),
    ("CharacterBody3D.move_and_slide", "bool"),
    ("CollisionObject2D.create_shape_owner", "int"),
    ("CollisionObject2D.get_rid", "RID"),
    ("CollisionObject2D.shape_owner_add_shape", "void"),
    ("CollisionObject3D.create_shape_owner", "int"),
    ("CollisionObject3D.get_rid", "RID"),
    ("CollisionObject3D.shape_owner_add_shape", "void"),
    ("Container.fit_child_in_rect", "void"),
    ("Container.queue_sort", "void"),
    ("Control.get_global_rect", "Rect2"),
    ("Control.get_minimum_size", "Vector2"),
    ("Control.get_rect", "Rect2"),
    ("Control.get_theme_color", "Color"),
    ("Control.get_theme_font", "Font"),
    ("Control.grab_focus", "void"),
    ("Control.has_focus", "bool"),
    ("Control.release_focus", "void"),
    ("Control.set_anchors_preset", "void"),
    ("Control.set_position", "void"),
    ("Control.set_size", "void"),
    ("Environment.get_background", "int"),
    ("Environment.get_glow_blend_mode", "int"),
    ("Environment.get_tonemapper", "int"),
    ("Environment.set_background", "void"),
    ("Environment.set_tonemapper", "void"),
    ("GeometryInstance3D.get_material_override", "Material"),
    ("GeometryInstance3D.set_material_override", "void"),
    ("ItemList.add_item", "int"),
    ("ItemList.clear", "void"),
    ("ItemList.get_item_count", "int"),
    ("ItemList.get_item_text", "String"),
    ("ItemList.get_selected_items", "PackedInt32Array"),
    ("ItemList.remove_item", "void"),
    ("ItemList.select", "void"),
    ("Label.get_text", "String"),
    ("Label.set_text", "void"),
    ("Light3D.get_color", "Color"),
    ("Light3D.set_color", "void"),
    ("LineEdit.clear", "void"),
    ("LineEdit.get_text", "String"),
    ("LineEdit.select_all", "void"),
    ("LineEdit.set_text", "void"),
    ("MeshInstance3D.get_mesh", "Mesh"),
    ("MeshInstance3D.get_surface_override_material", "Material"),
    ("MeshInstance3D.set_mesh", "void"),
    ("MeshInstance3D.set_surface_override_material", "void"),
    ("NavigationAgent2D.get_next_path_position", "Vector2"),
    ("NavigationAgent2D.is_navigation_finished", "bool"),
    ("NavigationAgent2D.is_target_reachable", "bool"),
    ("NavigationAgent2D.set_target_position", "void"),
    ("NavigationAgent3D.get_next_path_position", "Vector3"),
    ("NavigationAgent3D.is_navigation_finished", "bool"),
    ("NavigationAgent3D.is_target_reachable", "bool"),
    ("NavigationAgent3D.set_target_position", "void"),
    ("Node.add_child", "void"),
    ("Node.add_to_group", "void"),
    ("Node.call_deferred", "Variant"),
    ("Node.create_tween", "Tween"),
    ("Node.duplicate", "Node"),
    ("Node.find_child", "Node"),
    ("Node.find_children", "Array"),
    ("Node.get_child", "Node"),
    ("Node.get_child_count", "int"),
    ("Node.get_children", "Array"),
    ("Node.get_groups", "Array"),
    ("Node.get_index", "int"),
    ("Node.get_multiplayer_authority", "int"),
    ("Node.get_name", "StringName"),
    ("Node.get_node", "Node"),
    ("Node.get_node_or_null", "Node"),
    ("Node.get_parent", "Node"),
    ("Node.get_path", "NodePath"),
    ("Node.get_tree", "SceneTree"),
    ("Node.get_viewport", "Viewport"),
    ("Node.get_window", "Window"),
    ("Node.has_node", "bool"),
    ("Node.is_in_group", "bool"),
    ("Node.is_inside_tree", "bool"),
    ("Node.is_multiplayer_authority", "bool"),
    ("Node.is_node_ready", "bool"),
    ("Node.is_physics_processing", "bool"),
    ("Node.is_processing", "bool"),
    ("Node.move_child", "void"),
    ("Node.print_tree", "void"),
    ("Node.print_tree_pretty", "void"),
    ("Node.propagate_call", "void"),
    ("Node.queue_free", "void"),
    ("Node.remove_child", "void"),
    ("Node.remove_from_group", "void"),
    ("Node.reparent", "void"),
    ("Node.replace_by", "void"),
    ("Node.request_ready", "void"),
    ("Node.set_multiplayer_authority", "void"),
    ("Node.set_name", "void"),
    ("Node.set_physics_process", "void"),
    ("Node.set_process", "void"),
    ("Node.set_process_input", "void"),
    ("Node.set_process_unhandled_input", "void"),
    ("Node2D.apply_scale", "void"),
    ("Node2D.get_global_position", "Vector2"),
    ("Node2D.get_global_rotation", "float"),
    ("Node2D.get_global_scale", "Vector2"),
    ("Node2D.get_position", "Vector2"),
    ("Node2D.get_relative_transform_to_parent", "Transform2D"),
    ("Node2D.get_rotation", "float"),
    ("Node2D.get_scale", "Vector2"),
    ("Node2D.global_translate", "void"),
    ("Node2D.look_at", "void"),
    ("Node2D.move_local_x", "void"),
    ("Node2D.move_local_y", "void"),
    ("Node2D.rotate", "void"),
    ("Node2D.set_global_position", "void"),
    ("Node2D.set_global_rotation", "void"),
    ("Node2D.set_position", "void"),
    ("Node2D.set_rotation", "void"),
    ("Node2D.set_scale", "void"),
    ("Node2D.to_global", "Vector2"),
    ("Node2D.to_local", "Vector2"),
    ("Node2D.translate", "void"),
    ("Node3D.get_global_basis", "Basis"),
    ("Node3D.get_global_position", "Vector3"),
    ("Node3D.get_global_rotation", "Vector3"),
    ("Node3D.get_global_rotation_degrees", "Vector3"),
    ("Node3D.get_global_transform", "Transform3D"),
    ("Node3D.get_position", "Vector3"),
    ("Node3D.get_rotation", "Vector3"),
    ("Node3D.get_rotation_degrees", "Vector3"),
    ("Node3D.get_scale", "Vector3"),
    ("Node3D.get_transform", "Transform3D"),
    ("Node3D.global_rotate", "void"),
    ("Node3D.global_translate", "void"),
    ("Node3D.hide", "void"),
    ("Node3D.is_visible", "bool"),
    ("Node3D.is_visible_in_tree", "bool"),
    ("Node3D.look_at", "void"),
    ("Node3D.look_at_from_position", "void"),
    ("Node3D.orthonormalize", "void"),
    ("Node3D.rotate", "void"),
    ("Node3D.rotate_object_local", "void"),
    ("Node3D.rotate_x", "void"),
    ("Node3D.rotate_y", "void"),
    ("Node3D.rotate_z", "void"),
    ("Node3D.set_global_position", "void"),
    ("Node3D.set_global_rotation", "void"),
    ("Node3D.set_global_transform", "void"),
    ("Node3D.set_position", "void"),
    ("Node3D.set_rotation", "void"),
    ("Node3D.set_rotation_degrees", "void"),
    ("Node3D.set_scale", "void"),
    ("Node3D.show", "void"),
    ("Node3D.to_global", "Vector3"),
    ("Node3D.to_local", "Vector3"),
    ("Node3D.translate", "void"),
    ("Node3D.translate_object_local", "void"),
    ("Object.call", "Variant"),
    ("Object.call_deferred", "Variant"),
    ("Object.callv", "Variant"),
    ("Object.connect", "int"),
    ("Object.disconnect", "void"),
    ("Object.emit_signal", "int"),
    ("Object.free", "void"),
    ("Object.get", "Variant"),
    ("Object.get_class", "String"),
    ("Object.get_meta", "Variant"),
    ("Object.get_meta_list", "PackedStringArray"),
    ("Object.get_property_list", "Array"),
    ("Object.get_signal_list", "Array"),
    ("Object.has_meta", "bool"),
    ("Object.has_method", "bool"),
    ("Object.has_signal", "bool"),
    ("Object.is_class", "bool"),
    ("Object.is_connected", "bool"),
    ("Object.notification", "void"),
    ("Object.set", "void"),
    ("Object.set_deferred", "void"),
    ("Object.set_meta", "void"),
    ("PackedScene.instantiate", "Node"),
    ("PackedScene.pack", "int"),
    ("RayCast2D.force_raycast_update", "void"),
    ("RayCast2D.get_collider", "Object"),
    ("RayCast2D.get_collision_normal", "Vector2"),
    ("RayCast2D.get_collision_point", "Vector2"),
    ("RayCast2D.is_colliding", "bool"),
    ("RayCast3D.force_raycast_update", "void"),
    ("RayCast3D.get_collider", "Object"),
    ("RayCast3D.get_collision_normal", "Vector3"),
    ("RayCast3D.get_collision_point", "Vector3"),
    ("RayCast3D.is_colliding", "bool"),
    ("RefCounted.get_reference_count", "int"),
    ("Resource.duplicate", "Resource"),
    ("Resource.emit_changed", "void"),
    ("Resource.get_rid", "RID"),
    ("RichTextLabel.add_text", "void"),
    ("RichTextLabel.append_text", "void"),
    ("RichTextLabel.clear", "void"),
    ("RichTextLabel.get_total_character_count", "int"),
    ("RichTextLabel.newline", "void"),
    ("RichTextLabel.push_bold", "void"),
    ("RichTextLabel.push_color", "void"),
    ("RichTextLabel.push_italics", "void"),
    ("RigidBody2D.add_central_force", "void"),
    ("RigidBody2D.add_force", "void"),
    ("RigidBody2D.add_torque", "void"),
    ("RigidBody2D.apply_central_force", "void"),
    ("RigidBody2D.apply_central_impulse", "void"),
    ("RigidBody2D.apply_force", "void"),
    ("RigidBody2D.apply_impulse", "void"),
    ("RigidBody2D.apply_torque", "void"),
    ("RigidBody2D.apply_torque_impulse", "void"),
    ("RigidBody3D.add_central_force", "void"),
    ("RigidBody3D.add_force", "void"),
    ("RigidBody3D.add_torque", "void"),
    ("RigidBody3D.apply_central_force", "void"),
    ("RigidBody3D.apply_central_impulse", "void"),
    ("RigidBody3D.apply_force", "void"),
    ("RigidBody3D.apply_impulse", "void"),
    ("RigidBody3D.apply_torque", "void"),
    ("RigidBody3D.apply_torque_impulse", "void"),
    ("SceneTree.change_scene_to_file", "int"),
    ("SceneTree.change_scene_to_packed", "int"),
    ("SceneTree.create_timer", "SceneTreeTimer"),
    ("SceneTree.create_tween", "Tween"),
    ("SceneTree.get_current_scene", "Node"),
    ("SceneTree.get_first_node_in_group", "Node"),
    ("SceneTree.get_node_count", "int"),
    ("SceneTree.get_nodes_in_group", "Array"),
    ("SceneTree.get_root", "Window"),
    ("SceneTree.has_group", "bool"),
    ("SceneTree.quit", "void"),
    ("SceneTree.reload_current_scene", "int"),
    ("SceneTree.set_current_scene", "void"),
    ("Sprite2D.get_rect", "Rect2"),
    ("Sprite2D.get_texture", "Texture2D"),
    ("Sprite2D.is_flipped_h", "bool"),
    ("Sprite2D.is_flipped_v", "bool"),
    ("Sprite2D.set_texture", "void"),
    ("TextEdit.clear", "void"),
    ("TextEdit.copy", "void"),
    ("TextEdit.cut", "void"),
    ("TextEdit.get_line", "String"),
    ("TextEdit.get_line_count", "int"),
    ("TextEdit.get_text", "String"),
    ("TextEdit.has_selection", "bool"),
    ("TextEdit.insert_text_at_caret", "void"),
    ("TextEdit.paste", "void"),
    ("TextEdit.select_all", "void"),
    ("TextEdit.set_line", "void"),
    ("TextEdit.set_text", "void"),
    ("TextEdit.undo", "void"),
    ("Timer.get_time_left", "float"),
    ("Timer.is_stopped", "bool"),
    ("Timer.start", "void"),
    ("Timer.stop", "void"),
    ("Tween.chain", "Tween"),
    ("Tween.custom_step", "bool"),
    ("Tween.is_running", "bool"),
    ("Tween.is_valid", "bool"),
    ("Tween.kill", "void"),
    ("Tween.parallel", "Tween"),
    ("Tween.pause", "void"),
    ("Tween.play", "void"),
    ("Tween.set_ease", "Tween"),
    ("Tween.set_loops", "Tween"),
    ("Tween.set_parallel", "Tween"),
    ("Tween.set_pause_mode", "Tween"),
    ("Tween.set_process_mode", "Tween"),
    ("Tween.set_speed_scale", "Tween"),
    ("Tween.set_trans", "Tween"),
    ("Tween.stop", "void"),
    ("Tween.tween_callback", "PropertyTweener"),
    ("Tween.tween_interval", "PropertyTweener"),
    ("Tween.tween_method", "MethodTweener"),
    ("Tween.tween_property", "PropertyTweener"),
    ("Viewport.get_camera_2d", "Camera2D"),
    ("Viewport.get_camera_3d", "Camera3D"),
    ("Viewport.get_mouse_position", "Vector2"),
    ("Viewport.get_texture", "ViewportTexture"),
    ("Viewport.get_visible_rect", "Rect2"),
    ("Viewport.gui_get_focus_owner", "Control"),
    ("Viewport.set_input_as_handled", "void"),
    ("Window.get_size", "Vector2i"),
    ("Window.hide", "void"),
    ("Window.popup", "void"),
    ("Window.popup_centered", "void"),
    ("Window.popup_centered_ratio", "void"),
    ("Window.set_size", "void"),
    ("Window.show", "void"),
];
